# permissions for end users to view trustedcertificates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trustedcertificates-viewer-role
rules:
- apiGroups:
  - certificates.hpe.com
  resources:
  - trustedcertificates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.hpe.com
  resources:
  - trustedcertificates/status
  verbs:
  - get
