## Service account for the operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trustedcerts-operator
  namespace: {{ .Release.Namespace }}
---
## ClusterRole that allows cluster-wide access to 
## manage trustedcertficates CRs and configmaps
## and publish events
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: trustedcerts-operator-role
rules:
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certificates.hpe.com
  resources:
  - trustedcertificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certificates.hpe.com
  resources:
  - trustedcertificates/status
  verbs:
  - get
  - patch
  - update
---
## Bind the role to the operator
## service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trustedcerts-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trustedcerts-operator-role
subjects:
- kind: ServiceAccount
  name: trustedcerts-operator
  namespace: {{ .Release.Namespace }}