#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: scan-trivy
  labels:
    attestations.chainguard.dev/predicate-type: scan-trivy
spec:
  params:
  - name: IMAGE
    type: string
    description: container image name
  - name: COSIGN_REPOSITORY
    type: string
    description: OCI repository for cosign to push sbom attestation too
    default: ""
  - name: SIGSTORE_CT_LOG_PUBLIC_KEY_FILE
    type: string
    default: ""
    description: |
      Cosign requires the ct log public key when interacting with private instances
      Setting this env variable will over ride what is used to validate the SCT coming back from Fulcio.
  - name: FULCIO_ENDPOINT
    type: string
    description: address of sigstore PKI server
  - name: REKOR_ENDPOINT
    type: string
    description: cosign defaults to using the public instance of rekor at rekor.sigstore.dev. To configure the rekor server

  steps:
  - name: trivyscan
    image: docker.io/aquasec/trivy:0.29.2
    command: ["trivy"]
    args: [
      "image",
      "-format", "json",
      "-o", "/workspace/image.trivy",
      "$(params['IMAGE'])"
    ]

  - name: trivyscan-log
    image: gcr.io/oci-tekton-service-dev/jq
    script: |
      cat /workspace/image.trivy | jq '.' -rj | tee /workspace/image.trivy
  - name: publish-scan-results
    image: gcr.io/projectsigstore/cosign:v1.9.0
    timeout: 10m
    args: [
      "attest",
      # Use workload identity to access images
      "--k8s-keychain",
      # Disable timeout (registry http fallback takes more than the default)
      "--timeout=0",
      # Force the upload
      "--force",
      # Use the Rekor URL provided by the refresher.
      "--rekor-url", "$(params['REKOR_ENDPOINT'])",
      # Use the Fulcio URL provided by the refresher.
      "--fulcio-url", "$(params['FULCIO_ENDPOINT'])",
      # Use the "predicate" produced by the previous step.
      "--predicate", "/workspace/image.trivy",
      "$(params['IMAGE'])"
    ]
    env:
    - name: COSIGN_EXPERIMENTAL
      value: "1"
    - name: COSIGN_REPOSITORY
      value: $(params["COSIGN_REPOSITORY"])
    - name: SIGSTORE_CT_LOG_PUBLIC_KEY_FILE
      value: $(params["SIGSTORE_CT_LOG_PUBLIC_KEY_FILE"])
    volumeMounts:
    - mountPath: /data
      name: ctlog-public-key
    - name: oidc-info
      mountPath: /var/run/sigstore/cosign
  volumes:
  - name: oidc-info
    projected:
      sources:
        - serviceAccountToken:
            path: oidc-token
            expirationSeconds: 600 # Use as short-lived as possible.
            audience: sigstore
  - name: ctlog-public-key
    secret:
      items:
        - key: public
          path: ctlog-public.pem
      secretName: ctlog-public-key
      # This is marked as optional so that we can use with public Fulcio as
      # well by not specifying SIGSTORE_CT_LOG_PUBLIC_KEY_FILE.
      optional: true
