apiVersion: certificates.hpe.com/v1alpha1
kind: TrustedCertificates
metadata:
  name: shasta-platform
spec:
  sources: # single source, a pem bundle from unauthed vault source
    - name: vault-pki
      type: http
      config:
         url: "http://cray-vault.vault.svc.cluster.local:8200/v1/pki_common/ca_chain"
         encoding: "pem"
         format: "vault-pki-ca-chain"
  destinations: # manage three configmaps
    - name: services
      type: configmap
      config:
         name: trusted-ca-certificates
         namespace: services
         encoding: "pem"
         bundle_key: "certificate_authority.crt" # key used to store 'bundle' of all certs
    - name: sma
      type: configmap
      config:
         name: trusted-ca-certificates
         namespace: sma
         encoding: "pem"
         bundle_key: "certificate_authority.crt"
    - name: istio-system 
      type: configmap
      config:
         name: trusted-ca-certificates
         namespace: istio-system
         encoding: "pem"
         bundle_key: "certificate_authority.crt"
