---
apiVersion: v1
kind: Pod
metadata:
  name: jq
spec:
  containers:
    - command:
        - sleep
        - "6000"
      image: gcr.io/oci-tekton-service-dev/jq:latest
      name: bash
  imagePullSecrets:
  - name: registry-credentials

---
apiVersion: v1
kind: Pod
metadata:
  name: bash
spec:
  containers:
    - command:
        - sleep
        - "6000"
      image: gcr.io/oci-tekton-service-dev/bash@sha256:afbf52f9a6ce7a50f340537c64aab5ed1c027c777df15095b013109bee5b87ae
      name: bash
  imagePullSecrets:
    - name: registry-credentials
